# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/alex/Documents/Code/psvita-llm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/alex/Documents/Code/psvita-llm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alex/Documents/Code/psvita-llm/CMakeFiles /Users/alex/Documents/Code/psvita-llm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alex/Documents/Code/psvita-llm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named psvita-llm

# Build rule for target.
psvita-llm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 psvita-llm
.PHONY : psvita-llm

# fast build rule for target.
psvita-llm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psvita-llm.dir/build.make CMakeFiles/psvita-llm.dir/build
.PHONY : psvita-llm/fast

#=============================================================================
# Target rules for targets named psvita-llm-velf

# Build rule for target.
psvita-llm-velf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 psvita-llm-velf
.PHONY : psvita-llm-velf

# fast build rule for target.
psvita-llm-velf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psvita-llm-velf.dir/build.make CMakeFiles/psvita-llm-velf.dir/build
.PHONY : psvita-llm-velf/fast

#=============================================================================
# Target rules for targets named psvita-llm.self-self

# Build rule for target.
psvita-llm.self-self: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 psvita-llm.self-self
.PHONY : psvita-llm.self-self

# fast build rule for target.
psvita-llm.self-self/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psvita-llm.self-self.dir/build.make CMakeFiles/psvita-llm.self-self.dir/build
.PHONY : psvita-llm.self-self/fast

#=============================================================================
# Target rules for targets named psvita-llm.vpk-vpk

# Build rule for target.
psvita-llm.vpk-vpk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 psvita-llm.vpk-vpk
.PHONY : psvita-llm.vpk-vpk

# fast build rule for target.
psvita-llm.vpk-vpk/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psvita-llm.vpk-vpk.dir/build.make CMakeFiles/psvita-llm.vpk-vpk.dir/build
.PHONY : psvita-llm.vpk-vpk/fast

common/debugScreen.obj: common/debugScreen.c.obj
.PHONY : common/debugScreen.obj

# target to build an object file
common/debugScreen.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psvita-llm.dir/build.make CMakeFiles/psvita-llm.dir/common/debugScreen.c.obj
.PHONY : common/debugScreen.c.obj

common/debugScreen.i: common/debugScreen.c.i
.PHONY : common/debugScreen.i

# target to preprocess a source file
common/debugScreen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psvita-llm.dir/build.make CMakeFiles/psvita-llm.dir/common/debugScreen.c.i
.PHONY : common/debugScreen.c.i

common/debugScreen.s: common/debugScreen.c.s
.PHONY : common/debugScreen.s

# target to generate assembly for a file
common/debugScreen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psvita-llm.dir/build.make CMakeFiles/psvita-llm.dir/common/debugScreen.c.s
.PHONY : common/debugScreen.c.s

vita_llm.obj: vita_llm.c.obj
.PHONY : vita_llm.obj

# target to build an object file
vita_llm.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psvita-llm.dir/build.make CMakeFiles/psvita-llm.dir/vita_llm.c.obj
.PHONY : vita_llm.c.obj

vita_llm.i: vita_llm.c.i
.PHONY : vita_llm.i

# target to preprocess a source file
vita_llm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psvita-llm.dir/build.make CMakeFiles/psvita-llm.dir/vita_llm.c.i
.PHONY : vita_llm.c.i

vita_llm.s: vita_llm.c.s
.PHONY : vita_llm.s

# target to generate assembly for a file
vita_llm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psvita-llm.dir/build.make CMakeFiles/psvita-llm.dir/vita_llm.c.s
.PHONY : vita_llm.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... psvita-llm-velf"
	@echo "... psvita-llm.self-self"
	@echo "... psvita-llm.vpk-vpk"
	@echo "... psvita-llm"
	@echo "... common/debugScreen.obj"
	@echo "... common/debugScreen.i"
	@echo "... common/debugScreen.s"
	@echo "... vita_llm.obj"
	@echo "... vita_llm.i"
	@echo "... vita_llm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

